use_frameworks!

platform :ios, '8.0'
source "https://github.com/CocoaPods/Specs.git"

target 'ZKFoundation_Example' do
  pod 'ZKFoundation', :path => '../'
  pod 'Masonry'
  pod 'AXWebViewController', :git => 'https://github.com/kaiser143/AXWebViewController.git', :commit => '1995d7957dcdfa5698dd1e031e037d163c98e461'

 # target 'ZKFoundation_Tests' do
 #   inherit! :search_paths

 #   pod 'FBSnapshotTestCase'
 # end
end
