use_frameworks!

platform :ios, '8.0'

target 'ZKFoundation_Example' do
  pod 'ZKFoundation', :path => '../'
  pod 'Masonry'
  pod 'AXWebViewController', :git => 'https://github.com/kaiser143/AXWebViewController.git', :commit => '5cebcc4fcdb269cf96c80dc6893b653cc29be2bb'

 # target 'ZKFoundation_Tests' do
 #   inherit! :search_paths

 #   pod 'FBSnapshotTestCase'
 # end
end
