use_frameworks!

platform :ios, '8.0'
source "https://github.com/CocoaPods/Specs.git"

target 'ZKFoundation_Example' do
  pod 'ZKFoundation', :path => '../'
  pod 'Masonry'
  pod 'AXWebViewController'

 # target 'ZKFoundation_Tests' do
 #   inherit! :search_paths

 #   pod 'FBSnapshotTestCase'
 # end
end
